require("dragonwarrior.set")
require("dragonwarrior.keymap")
require("dragonwarrior.packer")
require("dragonwarrior.color")
require("dragonwarrior.rust_setup")
require("dragonwarrior.auto_completion_setup")
